---
title: "Prepara matriz de datos ambientales"
author: "ajpelu"
date: "2022-01-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE
)
```

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)
library(corrplot)
library(corrr)
library(factoextra)
library(kableExtra)
```


- Prepare data 

```{r}
rawdata <- readxl::read_excel(here::here("data/Tabla_variables_2012_2020.xls")) %>% dplyr::select(-contains("LS_B"), 
                -contains("MT_"), 
                -LS_NDVI, 
                -FR_OLIVO, -FR_EUCAL, 
                -FR_URBAN, -FR_AGUA,
                -FR_VIASC, -FR_CULTI,
                -DS_VIASC, -DS_URBAN, 
                -DS_LAGIN, -DS_AGUA, 
                -DS_RIOS, -DS_CULTI) %>% 
  rename(Pp_oto = "Precipitación Otoños",
         Pp_inv = "Precipitación Inviernos",
         PP_pri = "Precipitación Primaveras",
         Pp_ver = "Precipitación Veranos",
         tmed_oto = "Temperatura media Otoños",
         tmed_inv = "Temperatura media Inviernos",
         tmed_pri = "Temperatura media Primaveras",
         tmed_ver = "Temperatura media Veranos") 


# Mean of Annual precipitation
pp_anu_year <- rawdata %>% 
  dplyr::select(Abreviatura, contains("Acumulado ANUAL")) %>% 
  rowwise() %>% 
  mutate(m = mean(c_across(where(is.numeric)))) %>% 
  dplyr::select(Abreviatura, Pp_anu = m)

# Average of Mean temperature
temp_anu_year <- rawdata %>% 
  dplyr::select(Abreviatura, contains("Temperatura media")) %>% 
  rowwise() %>% 
  mutate(m = mean(c_across(where(is.numeric)))) %>% 
  dplyr::select(Abreviatura, temp_anu = m)


env <- rawdata %>% 
  inner_join(temp_anu_year) %>% 
  inner_join(pp_anu_year) %>% 
  dplyr::select(-contains("Temperatura media")) %>% 
  dplyr::select(-contains("Acumulado ANUAL")) %>% 
  rename(elev = "Elevación")
```

- climate data 


```{r}
library("xlsx")
rawclimate <- readxl::read_excel(
  here::here('data/Tabla_variables_modelización_lepidópteros_ACTUALIZADO_2020.xlsx'),
  sheet = 2, col_types = c("guess","guess", "guess", rep("numeric", 169)))
 
pp_inv_year <- rawclimate  %>% 
  dplyr::select(Id_transect, contains("Precipitación Invierno")) %>% 
  dplyr::select(Id_transect, contains("Acumulado")) %>% 
  pivot_longer(-Id_transect, names_to = c("year", "remove"),
               values_to = "p_inv_year",
               names_prefix = "Precipitación Invierno", 
               names_transform = list(year = as.integer),
               names_pattern = "(.*) (Acumulado trimestre)") %>% 
  dplyr::select(-remove)

pp_pri_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Precipitación Primavera")) %>% 
  dplyr::select(Id_transect, contains("Acumulado")) %>% 
  pivot_longer(-Id_transect, names_to = c("year", "remove"),
               values_to = "p_pri_year",
               names_prefix = "Precipitación Primavera",
               names_transform = list(year = as.integer),
               names_pattern = "(.*) (Acumulado trimestre)") %>% 
  dplyr::select(-remove)

pp_ver_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Precipitación Verano")) %>% 
  dplyr::select(Id_transect, contains("Acumulado")) %>% 
  pivot_longer(-Id_transect, names_to = c("year", "remove"),
               values_to = "p_ver_year",
               names_prefix = "Precipitación Verano", 
               names_transform = list(year = as.integer),
               names_pattern = "(.*) (Acumulado trimestre)") %>% 
  dplyr::select(-remove)

pp_oto_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Precipitación Otoño")) %>% 
  dplyr::select(Id_transect, contains("Acumulado")) %>% 
  pivot_longer(-Id_transect, names_to = c("year", "remove"),
               values_to = "p_oto_year",
               names_prefix = "Precipitación Otoño", 
               names_transform = list(year = as.integer),
               names_pattern = "(.*) (Acumulado trimestre)") %>% 
  dplyr::select(-remove)

pp_anu_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Acumulado ANUAL")) %>% 
  pivot_longer(-Id_transect, names_to = c("year", "remove"),
               names_prefix = "Precipitación", 
               values_to = "p_anu_year",
               names_transform = list(year = as.integer),
               names_pattern = "(.*) (Acumulado ANUAL)") %>% 
  dplyr::select(-remove)
pp_season <- pp_anu_year %>% 
  inner_join(pp_pri_year) %>% 
  inner_join(pp_ver_year) %>% 
  inner_join(pp_oto_year) %>%  
  inner_join(pp_inv_year) 


t_inv_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Temperatura Invierno")) %>% 
  pivot_longer(-Id_transect, names_to = c("year"),
               values_to = "t_inv_year",
               names_prefix = "Temperatura Invierno", 
               names_transform = list(year = as.integer)) 
t_ver_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Temperatura Verano")) %>% 
  pivot_longer(-Id_transect, names_to = c("year"),
               values_to = "t_ver_year",
               names_prefix = "Temperatura Verano", 
               names_transform = list(year = as.integer)) 
t_pri_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Temperatura Primavera")) %>% 
  pivot_longer(-Id_transect, names_to = c("year"),
               values_to = "t_pri_year",
               names_prefix = "Temperatura Primavera", 
               names_transform = list(year = as.integer)) 
t_oto_year <- rawclimate %>% 
  dplyr::select(Id_transect, contains("Temperatura Otoño")) %>% 
  pivot_longer(-Id_transect, names_to = c("year"),
               values_to = "t_oto_year",
               names_prefix = "Temperatura Otoño", 
               names_transform = list(year = as.integer)) 
t_year <- t_pri_year %>% 
  inner_join(t_ver_year) %>% 
  inner_join(t_oto_year) %>%  
  inner_join(t_inv_year) %>% 
  rowwise() %>% 
  mutate(t_anual = mean(t_pri_year, t_oto_year, t_inv_year, t_ver_year))
```


```{r}
climate_year <- pp_season %>% inner_join(t_year)
write_csv(climate_year, here::here("data/climate_year.csv"))
```

## Correlation bewteen variables

```{r}
# Escalamos las variables 
env_selecccion <- env %>% 
  dplyr::select(-Transecto, -Id_transect, -Abreviatura, -Longitud)

env.scale <- scale(env_selecccion)

# correlaciones 
env.correlations <- cor(env.scale) # res
symnum(env.correlations , abbr.colnames = FALSE) %>% kbl()
dfdis <- dist(env.correlations, method = "euclidean")
```

- Generamos un plot de correlaciones

```{r}
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}

p.mat <- cor.mtest(env.scale)

corrplot::corrplot(env.correlations, type = "upper", tl.col = "black", tl.srt = 90, tl.cex = 0.4,
         p.mat = p.mat, sig.level = 0.05, 
         insig = "blank", 
         diag = FALSE)

```


```{r}
pdf(here::here("figs/correlation_env_variables_numbers.pdf"))
corrplot::corrplot(env.correlations, method = "number",
                   type = "upper", tl.col = "black", 
                   col= "black", tl.srt = 90, tl.cex = 0.35, 
                   number.cex = .3, number.digits = 2,
         diag = FALSE)
dev.off()

pdf(here::here("figs/correlation_env_variables.pdf"))
corrplot::corrplot(env.correlations, type = "upper",
                   tl.col = "black", tl.srt = 90, tl.cex = 0.4,
         p.mat = p.mat, sig.level = 0.05, 
         insig = "blank", 
         diag = FALSE)
dev.off()
```

- Table of correlations
```{r}
dfscale_corrr <- correlate(env.scale)
dfscale_corrr %>% shave(upper = FALSE) %>%
  fashion() %>% kbl()
```

- Hierarchical cluster

```{r}
# library("pvclust")
# fit <- hclust(dfdis, method="ward")
# plot(fit, cex = .6)
# 33 Variables 
# Vamos a probar a reducir a 10
h <- hcut(dfdis, k=14)
dendro <- fviz_dend(h, rect = TRUE, horiz = TRUE, lwd = 0.5, cex = .5)
dendro
ggsave(here::here("figs/dendrograma_env.pdf"), 
       height = 7, width = 5, device = "pdf")
```

## Selección final de variables

```{r}
variables_sel <- c("Pp_anu", "TP_PEND", "FR_MATDE", 
             "TP_SU_NO", "FR_QUERC", "FR_CONIF", 
             "TP_RSH_V", "HIDRO_ITH", "temp_anu",
             "TP_RSD_P", "Pp_ver", "TP_ES_OE", "TP_EXPO",
             "DS_ARBOL", "elev")

env_seleccionadas <- env %>% dplyr::select(Transecto,Id_transect,Abreviatura, matches(variables_sel)) 


write_csv(env_seleccionadas, here::here("data/matrix_env_variables_selected.csv"))
```
